[package]
name = "solana-sbf-rust-secp256k1-recover"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
libsecp256k1 = { workspace = true }
sha3 = { workspace = true }
solana-hash = { workspace = true }
solana-keccak-hasher = { workspace = true, features = ["sha3"] }
solana-msg = { workspace = true }
solana-program-entrypoint = { workspace = true }
solana-secp256k1-recover = { workspace = true }

[lints]
workspace = true
