[package]
name = "solana-votor-messages"
documentation = "https://docs.rs/solana-votor-messages"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
frozen-abi = ["dep:solana-frozen-abi", "dep:solana-frozen-abi-macro"]

[dependencies]
serde = { workspace = true }
solana-bls-signatures = { workspace = true, features = [
    "bytemuck", "solana-signer-derive",
] }
solana-clock = { workspace = true }
solana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
solana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
solana-hash = { workspace = true, features = ["serde"] }
solana-logger = { workspace = true }

[lints]
workspace = true
