[package]
name = "solana-sbf-rust-sha"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
blake3 = { workspace = true }
solana-blake3-hasher = { workspace = true }
solana-keccak-hasher = { workspace = true }
solana-msg = { workspace = true }
solana-program-entrypoint = { workspace = true }
solana-sha256-hasher = { workspace = true }

[lints]
workspace = true
